import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Home/LandingPages/Navbar";
import UserHome from "@/components/Home/LandingPages/UserHome";
import Login from "@/components/auth/Common/Login/Login";
import StreamerRegister from "@/components/auth/Streamer/StreamerRegister";
import StreamerLogin from "@/components/auth/Streamer/StreamerLogin";


const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <Navbar/>
       <Login/> */}
      <StreamerLogin/>
        

        {/* <UserHome/> */}
        {children}
      </body>
    </html>
  );
}
